# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(max_length=120),
        ),
    ]
