# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170320_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_ID',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='GoogleProfile',
        ),
    ]
