# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170320_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
